{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNN0ISPTxNsGU4rX/MWYJXt",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Giovasosa/Tarea-IA/blob/main/multiagentes.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "nK_PpygreDA2"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "f1402e84"
      },
      "outputs": [],
      "source": [
        "!pip install -q transformers sentence-transformers scikit-learn pandas numpy torch faiss-cpu"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "bdac46d0"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import io\n",
        "import faiss\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
        "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.model_selection import cross_val_score\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from transformers import pipeline"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 404
        },
        "id": "1e563d79",
        "outputId": "4d95d970-cd02-4d1b-bef2-ea630438451f"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dataset: 600 filas x 8 columnas (4800 celdas)\n",
            "Valores nulos: 78\n",
            "rendimiento\n",
            "alto     223\n",
            "medio    213\n",
            "bajo     164\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "     nombre  edad  nota_matematica  nota_lengua  nota_ciencias  \\\n",
              "0     Ana_1    17              7.9          6.0            7.5   \n",
              "1   Bruno_2    18              6.0          3.6            5.2   \n",
              "2   Carla_3    16              5.9          6.4            5.9   \n",
              "3   Diego_4    18              3.5          4.0            3.5   \n",
              "4   Elena_5    18              NaN          4.6            3.3   \n",
              "5  Franco_6    15             10.0          9.2            7.5   \n",
              "6  Gisela_7    16              3.4          3.9            4.2   \n",
              "7  Hernan_8    16              5.7          6.9            5.0   \n",
              "\n",
              "   asistencia_pct   turno rendimiento  \n",
              "0            76.5   tarde       medio  \n",
              "1            71.0  manana        bajo  \n",
              "2            74.1   tarde       medio  \n",
              "3            48.6   tarde        bajo  \n",
              "4            63.1  manana        bajo  \n",
              "5            92.8   tarde        alto  \n",
              "6            60.7   tarde        bajo  \n",
              "7            69.2  manana       medio  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-df7121ff-0600-4520-bd8c-149c976587e9\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>nombre</th>\n",
              "      <th>edad</th>\n",
              "      <th>nota_matematica</th>\n",
              "      <th>nota_lengua</th>\n",
              "      <th>nota_ciencias</th>\n",
              "      <th>asistencia_pct</th>\n",
              "      <th>turno</th>\n",
              "      <th>rendimiento</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Ana_1</td>\n",
              "      <td>17</td>\n",
              "      <td>7.9</td>\n",
              "      <td>6.0</td>\n",
              "      <td>7.5</td>\n",
              "      <td>76.5</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Bruno_2</td>\n",
              "      <td>18</td>\n",
              "      <td>6.0</td>\n",
              "      <td>3.6</td>\n",
              "      <td>5.2</td>\n",
              "      <td>71.0</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Carla_3</td>\n",
              "      <td>16</td>\n",
              "      <td>5.9</td>\n",
              "      <td>6.4</td>\n",
              "      <td>5.9</td>\n",
              "      <td>74.1</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Diego_4</td>\n",
              "      <td>18</td>\n",
              "      <td>3.5</td>\n",
              "      <td>4.0</td>\n",
              "      <td>3.5</td>\n",
              "      <td>48.6</td>\n",
              "      <td>tarde</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Elena_5</td>\n",
              "      <td>18</td>\n",
              "      <td>NaN</td>\n",
              "      <td>4.6</td>\n",
              "      <td>3.3</td>\n",
              "      <td>63.1</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>Franco_6</td>\n",
              "      <td>15</td>\n",
              "      <td>10.0</td>\n",
              "      <td>9.2</td>\n",
              "      <td>7.5</td>\n",
              "      <td>92.8</td>\n",
              "      <td>tarde</td>\n",
              "      <td>alto</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>Gisela_7</td>\n",
              "      <td>16</td>\n",
              "      <td>3.4</td>\n",
              "      <td>3.9</td>\n",
              "      <td>4.2</td>\n",
              "      <td>60.7</td>\n",
              "      <td>tarde</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>Hernan_8</td>\n",
              "      <td>16</td>\n",
              "      <td>5.7</td>\n",
              "      <td>6.9</td>\n",
              "      <td>5.0</td>\n",
              "      <td>69.2</td>\n",
              "      <td>manana</td>\n",
              "      <td>medio</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-df7121ff-0600-4520-bd8c-149c976587e9')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-df7121ff-0600-4520-bd8c-149c976587e9 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-df7121ff-0600-4520-bd8c-149c976587e9');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_raw",
              "summary": "{\n  \"name\": \"df_raw\",\n  \"rows\": 600,\n  \"fields\": [\n    {\n      \"column\": \"nombre\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 600,\n        \"samples\": [\n          \"Karen_111\",\n          \"Tomas_420\",\n          \"Pablo_566\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"edad\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 14,\n        \"max\": 18,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          18,\n          14,\n          16\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_matematica\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2.1107708594993513,\n        \"min\": 1.0,\n        \"max\": 10.0,\n        \"num_unique_values\": 83,\n        \"samples\": [\n          2.4,\n          7.9,\n          4.3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_lengua\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.9252192845175486,\n        \"min\": 1.5,\n        \"max\": 10.0,\n        \"num_unique_values\": 79,\n        \"samples\": [\n          5.0,\n          6.0,\n          7.2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_ciencias\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2.0160845668464216,\n        \"min\": 1.0,\n        \"max\": 10.0,\n        \"num_unique_values\": 84,\n        \"samples\": [\n          1.0,\n          7.5,\n          7.4\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"asistencia_pct\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 15.111630872220658,\n        \"min\": 40.0,\n        \"max\": 100.0,\n        \"num_unique_values\": 340,\n        \"samples\": [\n          60.4,\n          48.2,\n          62.6\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"turno\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"manana\",\n          \"tarde\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"rendimiento\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"medio\",\n          \"bajo\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 3
        }
      ],
      "source": [
        "def generar_dataset(n: int = 600, seed: int = 42) -> pd.DataFrame:\n",
        "    \"\"\"Genera un dataset sintético de estudiantes con ~5 % de nulos.\"\"\"\n",
        "    np.random.seed(seed)\n",
        "\n",
        "    nombres_base = [\n",
        "        \"Ana\", \"Bruno\", \"Carla\", \"Diego\", \"Elena\", \"Franco\", \"Gisela\",\n",
        "        \"Hernan\", \"Ivana\", \"Juan\", \"Karen\", \"Lucas\", \"Maria\", \"Nicolas\",\n",
        "        \"Olivia\", \"Pablo\", \"Quimey\", \"Rodrigo\", \"Sofia\", \"Tomas\",\n",
        "        \"Valentina\", \"Walter\", \"Ximena\", \"Yamila\", \"Zaira\", \"Agustin\",\n",
        "        \"Belen\", \"Cesar\", \"Daniela\", \"Emilio\", \"Florencia\", \"Gaston\",\n",
        "        \"Hilda\", \"Ignacio\", \"Julia\", \"Kevin\", \"Lorena\", \"Marcos\",\n",
        "        \"Noelia\", \"Omar\", \"Patricia\", \"Quintin\", \"Raquel\", \"Santiago\",\n",
        "        \"Teresa\", \"Uriel\", \"Veronica\", \"William\", \"Ximena\", \"Yolanda\",\n",
        "    ]\n",
        "\n",
        "    nombres   = [f\"{nombres_base[i % len(nombres_base)]}_{i + 1}\" for i in range(n)]\n",
        "    edades    = np.random.randint(14, 19, size=n)\n",
        "    turnos    = np.random.choice([\"manana\", \"tarde\"], size=n, p=[0.55, 0.45])\n",
        "\n",
        "    rendimiento_list, nota_mat, nota_len, nota_cie, asistencia = [], [], [], [], []\n",
        "\n",
        "    for i in range(n):\n",
        "        bonus = 0.3 if turnos[i] == \"manana\" else 0.0\n",
        "        r = np.random.choice([\"alto\", \"medio\", \"bajo\"], p=[0.35, 0.35, 0.30])\n",
        "        rendimiento_list.append(r)\n",
        "\n",
        "        if r == \"alto\":\n",
        "            nota_mat.append(round(np.clip(np.random.normal(8.5 + bonus, 0.8), 7.0, 10.0), 1))\n",
        "            nota_len.append(round(np.clip(np.random.normal(8.5 + bonus, 0.7), 7.0, 10.0), 1))\n",
        "            nota_cie.append(round(np.clip(np.random.normal(8.3 + bonus, 0.9), 7.0, 10.0), 1))\n",
        "            asistencia.append(round(np.clip(np.random.normal(92, 5), 80, 100), 1))\n",
        "        elif r == \"medio\":\n",
        "            nota_mat.append(round(np.clip(np.random.normal(6.5, 0.9), 5.0, 8.5), 1))\n",
        "            nota_len.append(round(np.clip(np.random.normal(6.8, 0.8), 5.0, 8.5), 1))\n",
        "            nota_cie.append(round(np.clip(np.random.normal(6.5, 1.0), 5.0, 8.5), 1))\n",
        "            asistencia.append(round(np.clip(np.random.normal(78, 7), 65, 90), 1))\n",
        "        else:\n",
        "            nota_mat.append(round(np.clip(np.random.normal(4.0, 1.0), 1.0, 6.0), 1))\n",
        "            nota_len.append(round(np.clip(np.random.normal(4.2, 0.9), 1.0, 6.0), 1))\n",
        "            nota_cie.append(round(np.clip(np.random.normal(3.9, 1.1), 1.0, 6.0), 1))\n",
        "            asistencia.append(round(np.clip(np.random.normal(58, 8), 40, 72), 1))\n",
        "\n",
        "    nota_mat_arr = np.array(nota_mat, dtype=float)\n",
        "    nota_len_arr = np.array(nota_len, dtype=float)\n",
        "    nota_cie_arr = np.array(nota_cie, dtype=float)\n",
        "\n",
        "    nota_mat_arr[np.random.choice(n, size=int(n * 0.05), replace=False)] = np.nan\n",
        "    nota_len_arr[np.random.choice(n, size=int(n * 0.04), replace=False)] = np.nan\n",
        "    nota_cie_arr[np.random.choice(n, size=int(n * 0.04), replace=False)] = np.nan\n",
        "\n",
        "    df = pd.DataFrame({\n",
        "        \"nombre\":          nombres,\n",
        "        \"edad\":            edades,\n",
        "        \"nota_matematica\": nota_mat_arr,\n",
        "        \"nota_lengua\":     nota_len_arr,\n",
        "        \"nota_ciencias\":   nota_cie_arr,\n",
        "        \"asistencia_pct\":  asistencia,\n",
        "        \"turno\":           turnos,\n",
        "        \"rendimiento\":     rendimiento_list,\n",
        "    })\n",
        "\n",
        "    print(f\"Dataset: {df.shape[0]} filas x {df.shape[1]} columnas ({df.size} celdas)\")\n",
        "    print(f\"Valores nulos: {df.isnull().sum().sum()}\")\n",
        "    print(df['rendimiento'].value_counts().to_string())\n",
        "    return df\n",
        "\n",
        "df_raw = generar_dataset(n=600, seed=42)\n",
        "df_raw.head(8)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 414
        },
        "id": "58326945",
        "outputId": "beaa1223-8fb3-4ae1-e6bf-f53a70caf2a6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "=======================================================\n",
            "AGENTE 1 — Normalizador\n",
            "=======================================================\n",
            "  [Limpieza] Nulos encontrados: 78\n",
            "  [Imputación] 'nota_matematica' -> mediana (6.80)\n",
            "  [Imputación] 'nota_lengua' -> mediana (7.10)\n",
            "  [Imputación] 'nota_ciencias' -> mediana (6.70)\n",
            "  [Codificación] 'turno' -> ['manana', 'tarde']\n",
            "  [Codificación] 'rendimiento' -> [np.str_('alto'), np.str_('bajo'), np.str_('medio')]\n",
            "  [Escalado] StandardScaler en: ['edad', 'nota_matematica', 'nota_lengua', 'nota_ciencias', 'asistencia_pct']\n",
            "\n",
            "Dataset limpio: (600, 10)\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "    nombre      edad  nota_matematica  nota_lengua  nota_ciencias  \\\n",
              "0    Ana_1  0.683739         0.634225    -0.456422       0.482130   \n",
              "1  Bruno_2  1.380247        -0.289876    -1.729417      -0.683088   \n",
              "2  Carla_3 -0.012769        -0.338513    -0.244256      -0.328457   \n",
              "3  Diego_4  1.380247        -1.505798    -1.517251      -1.544337   \n",
              "4  Elena_5  1.380247         0.099219    -1.199002      -1.645660   \n",
              "\n",
              "   asistencia_pct   turno rendimiento  turno_enc  rendimiento_enc  \n",
              "0       -0.086948   tarde       medio          1                2  \n",
              "1       -0.451210  manana        bajo          0                1  \n",
              "2       -0.245899   tarde       medio          1                2  \n",
              "3       -1.934749   tarde        bajo          1                1  \n",
              "4       -0.974422  manana        bajo          0                1  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>nombre</th>\n",
              "      <th>edad</th>\n",
              "      <th>nota_matematica</th>\n",
              "      <th>nota_lengua</th>\n",
              "      <th>nota_ciencias</th>\n",
              "      <th>asistencia_pct</th>\n",
              "      <th>turno</th>\n",
              "      <th>rendimiento</th>\n",
              "      <th>turno_enc</th>\n",
              "      <th>rendimiento_enc</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Ana_1</td>\n",
              "      <td>0.683739</td>\n",
              "      <td>0.634225</td>\n",
              "      <td>-0.456422</td>\n",
              "      <td>0.482130</td>\n",
              "      <td>-0.086948</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "      <td>1</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Bruno_2</td>\n",
              "      <td>1.380247</td>\n",
              "      <td>-0.289876</td>\n",
              "      <td>-1.729417</td>\n",
              "      <td>-0.683088</td>\n",
              "      <td>-0.451210</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Carla_3</td>\n",
              "      <td>-0.012769</td>\n",
              "      <td>-0.338513</td>\n",
              "      <td>-0.244256</td>\n",
              "      <td>-0.328457</td>\n",
              "      <td>-0.245899</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "      <td>1</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Diego_4</td>\n",
              "      <td>1.380247</td>\n",
              "      <td>-1.505798</td>\n",
              "      <td>-1.517251</td>\n",
              "      <td>-1.544337</td>\n",
              "      <td>-1.934749</td>\n",
              "      <td>tarde</td>\n",
              "      <td>bajo</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Elena_5</td>\n",
              "      <td>1.380247</td>\n",
              "      <td>0.099219</td>\n",
              "      <td>-1.199002</td>\n",
              "      <td>-1.645660</td>\n",
              "      <td>-0.974422</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_limpio",
              "summary": "{\n  \"name\": \"df_limpio\",\n  \"rows\": 600,\n  \"fields\": [\n    {\n      \"column\": \"nombre\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 600,\n        \"samples\": [\n          \"Karen_111\",\n          \"Tomas_420\",\n          \"Pablo_566\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"edad\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488732,\n        \"min\": -1.4057855414930898,\n        \"max\": 1.380246910681488,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          1.380246910681488,\n          -1.4057855414930898,\n          -0.012769315405800908\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_matematica\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488719,\n        \"min\": -2.7217207755665975,\n        \"max\": 1.6555999857092034,\n        \"num_unique_values\": 83,\n        \"samples\": [\n          -2.0408042127014734,\n          0.6342251414115166,\n          0.43967755202148084\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_lengua\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488723,\n        \"min\": -2.8432872660777737,\n        \"max\": 1.665236521192272,\n        \"num_unique_values\": 79,\n        \"samples\": [\n          -0.9868362948489313,\n          -0.4564217316406906,\n          0.18007574420919825\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_ciencias\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488725,\n        \"min\": -2.8108785317945593,\n        \"max\": 1.7486721055411636,\n        \"num_unique_values\": 84,\n        \"samples\": [\n          -1.7469833830828907,\n          0.48213026183679614,\n          -0.7337499081193969\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"asistencia_pct\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488714,\n        \"min\": -2.5043215911593095,\n        \"max\": 1.4694429280178285,\n        \"num_unique_values\": 340,\n        \"samples\": [\n          -1.153241654639083,\n          -1.9612404402051007,\n          -1.0075369556025875\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"turno\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"manana\",\n          \"tarde\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"rendimiento\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"medio\",\n          \"bajo\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"turno_enc\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"rendimiento_enc\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 2,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          2,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 4
        }
      ],
      "source": [
        "class AgenteNormalizador:\n",
        "    def __init__(self):\n",
        "        self.scaler         = StandardScaler()\n",
        "        self.label_encoders = {}\n",
        "        self.log            = []\n",
        "\n",
        "    def limpiar(self, df):\n",
        "        nulos = df.isnull().sum().sum()\n",
        "        df    = df.drop_duplicates()\n",
        "        self.log.append(f\"[Limpieza] Nulos encontrados: {nulos}\")\n",
        "        return df\n",
        "\n",
        "    def imputar(self, df):\n",
        "        for col in df.columns:\n",
        "            if df[col].isnull().any():\n",
        "                if df[col].dtype in [\"float64\", \"int64\"]:\n",
        "                    val = df[col].median()\n",
        "                    df[col] = df[col].fillna(val)\n",
        "                    self.log.append(f\"[Imputación] '{col}' -> mediana ({val:.2f})\")\n",
        "                else:\n",
        "                    val = df[col].mode()[0]\n",
        "                    df[col] = df[col].fillna(val)\n",
        "                    self.log.append(f\"[Imputación] '{col}' -> moda ('{val}')\")\n",
        "        return df\n",
        "\n",
        "    def codificar(self, df, cols):\n",
        "        for col in cols:\n",
        "            le = LabelEncoder()\n",
        "            df[col + \"_enc\"] = le.fit_transform(df[col].astype(str))\n",
        "            self.label_encoders[col] = le\n",
        "            self.log.append(f\"[Codificación] '{col}' -> {list(le.classes_)}\")\n",
        "        return df\n",
        "\n",
        "    def escalar(self, df, cols):\n",
        "        df[cols] = self.scaler.fit_transform(df[cols])\n",
        "        self.log.append(f\"[Escalado] StandardScaler en: {cols}\")\n",
        "        return df\n",
        "\n",
        "    def procesar(self, df):\n",
        "        print(\"=\" * 55)\n",
        "        print(\"AGENTE 1 — Normalizador\")\n",
        "        print(\"=\" * 55)\n",
        "        df = self.limpiar(df.copy())\n",
        "        df = self.imputar(df)\n",
        "        df = self.codificar(df, [\"turno\", \"rendimiento\"])\n",
        "        df = self.escalar(df, [\"edad\", \"nota_matematica\", \"nota_lengua\", \"nota_ciencias\", \"asistencia_pct\"])\n",
        "        for e in self.log:\n",
        "            print(\" \", e)\n",
        "        print(f\"\\nDataset limpio: {df.shape}\")\n",
        "        return df\n",
        "\n",
        "agente1   = AgenteNormalizador()\n",
        "df_limpio = agente1.procesar(df_raw)\n",
        "df_limpio.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "background_save": true,
          "base_uri": "https://localhost:8080/",
          "height": 225,
          "referenced_widgets": [
            "5b841d8751074704b004b71cec81077e"
          ]
        },
        "id": "9cc88377",
        "outputId": "7d4c983d-650a-4455-8255-b765e3bfaa16"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "=======================================================\n",
            "AGENTE 2 — Entrenador\n",
            "=======================================================\n",
            "  Cargando embedder: all-MiniLM-L6-v2\n"
          ]
        },
        {
          "data": {
            "application/vnd.jupyter.widget-view+json": {
              "model_id": "5b841d8751074704b004b71cec81077e",
              "version_major": 2,
              "version_minor": 0
            },
            "text/plain": [
              "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
            ]
          },
          "metadata": {},
          "output_type": "display_data"
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "  [Embeddings] Generando representaciones semánticas...\n",
            "  [Embeddings] Shape: (600, 384)\n",
            "  [Features] 6 numéricas + 384 embedding = 390 total\n",
            "\n",
            "  [Entrenamiento] Validación cruzada cv=5:\n",
            "    Random Forest: 0.9833 +/- 0.0091\n",
            "    Gradient Boosting: 0.9883 +/- 0.0113\n",
            "    Logistic Regression: 0.9917 +/- 0.0075\n",
            "\n",
            "  Mejor modelo: Logistic Regression (0.9917)\n"
          ]
        }
      ],
      "source": [
        "class AgenteEntrenador:\n",
        "    def __init__(self, modelo_emb=\"all-MiniLM-L6-v2\"):\n",
        "        print(\"=\" * 55)\n",
        "        print(\"AGENTE 2 — Entrenador\")\n",
        "        print(\"=\" * 55)\n",
        "        print(f\"  Cargando embedder: {modelo_emb}\")\n",
        "        self.embedder      = SentenceTransformer(modelo_emb)\n",
        "        self.mejor_modelo  = None\n",
        "        self.mejor_score   = 0\n",
        "        self.mejor_nombre  = \"\"\n",
        "        self.metricas      = {}\n",
        "\n",
        "    def generar_embeddings(self, df_orig):\n",
        "        print(\"\\n  [Embeddings] Generando representaciones semánticas...\")\n",
        "        textos = df_orig.apply(\n",
        "            lambda r: (\n",
        "                f\"estudiante de {r['edad']} anios, turno {r['turno']}, \"\n",
        "                f\"notas: matematica {r['nota_matematica']}, \"\n",
        "                f\"lengua {r['nota_lengua']}, ciencias {r['nota_ciencias']}, \"\n",
        "                f\"asistencia {r['asistencia_pct']}%\"\n",
        "            ),\n",
        "            axis=1,\n",
        "        ).tolist()\n",
        "        emb = self.embedder.encode(textos, show_progress_bar=False)\n",
        "        print(f\"  [Embeddings] Shape: {emb.shape}\")\n",
        "        return emb\n",
        "\n",
        "    def construir_features(self, df, emb):\n",
        "        cols = [\"edad\", \"nota_matematica\", \"nota_lengua\", \"nota_ciencias\", \"asistencia_pct\", \"turno_enc\"]\n",
        "        X = np.hstack([df[cols].values, emb])\n",
        "        print(f\"  [Features] {len(cols)} numéricas + {emb.shape[1]} embedding = {X.shape[1]} total\")\n",
        "        return X\n",
        "\n",
        "    def entrenar(self, X, y):\n",
        "        print(\"\\n  [Entrenamiento] Validación cruzada cv=5:\")\n",
        "        candidatos = {\n",
        "            \"Random Forest\":       RandomForestClassifier(n_estimators=100, random_state=42),\n",
        "            \"Gradient Boosting\":   GradientBoostingClassifier(n_estimators=100, random_state=42),\n",
        "            \"Logistic Regression\": LogisticRegression(max_iter=500, random_state=42),\n",
        "        }\n",
        "        for nombre, modelo in candidatos.items():\n",
        "            scores = cross_val_score(modelo, X, y, cv=5, scoring=\"accuracy\")\n",
        "            m, s   = scores.mean(), scores.std()\n",
        "            self.metricas[nombre] = {\"accuracy_media\": round(m, 4), \"std\": round(s, 4)}\n",
        "            print(f\"    {nombre}: {m:.4f} +/- {s:.4f}\")\n",
        "            if m > self.mejor_score:\n",
        "                self.mejor_score  = m\n",
        "                self.mejor_nombre = nombre\n",
        "                self.mejor_modelo = modelo\n",
        "        self.mejor_modelo.fit(X, y)\n",
        "        print(f\"\\n  Mejor modelo: {self.mejor_nombre} ({self.mejor_score:.4f})\")\n",
        "\n",
        "    def procesar(self, df, df_orig):\n",
        "        emb = self.generar_embeddings(df_orig)\n",
        "        X   = self.construir_features(df, emb)\n",
        "        y   = df[\"rendimiento_enc\"].values\n",
        "        self.entrenar(X, y)\n",
        "        return {\n",
        "            \"modelo\":         self.mejor_modelo,\n",
        "            \"nombre_modelo\":  self.mejor_nombre,\n",
        "            \"metricas\":       self.metricas,\n",
        "            \"mejor_accuracy\": self.mejor_score,\n",
        "            \"X\": X, \"y\": y,\n",
        "        }\n",
        "\n",
        "agente2   = AgenteEntrenador()\n",
        "resultado = agente2.procesar(df_limpio, df_raw)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "b862d50b",
        "outputId": "755274e9-5572-4ce3-c122-065cc71aa7ec",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000,
          "referenced_widgets": [
            "cf054edc28934f45af3f634c5f2e5a86",
            "d01ebe6441424a0ea04a3e1b18fd3818",
            "cb97c17cb9234aeb99fdb6261777e99a",
            "6633b44ef9f844da9c5a566086129041",
            "a42af2339e5b4de4b54f907a3eb9c143",
            "cc953baacd6f448a8d8ea6bb4b2a8fd4",
            "8c2d2e337d75432d80477d10ea97e5e4",
            "9a3e8244d54d4e9d9ef6abdc5b025d5e",
            "96f3c7fd53fa42b7961d4681c7aa457a",
            "59ee7a73b8d9468b903d1be37c3f3996",
            "e06088293597433385aa166db52ace1b",
            "0972c7bce4d24ab7a69f209952eb4eb0",
            "3bf451594c2a4c529189b811fd68b003",
            "79f03ec0d5ff46aabf5f9ea5b68c7136",
            "4c0bb87cc6bb4c6f9fa43ad479522b4a",
            "ac048eb39b614d03b6f956f925cdbd03",
            "1f9c2e66426545eba617e33386cf6045",
            "bfa3f60f3ffa42ada8ca7b30af797b5f",
            "0944a5350a194fbcb3821f2f69913b9e",
            "1fbe372f60724a7986d76eba14327f8f",
            "2e518efb17204defa36594c5fe57bcb2",
            "9e28010d484043e4b1c2119763f00858",
            "bf67bf2af47541a8ac25e32c6321b0b7",
            "1ce048fcee7e47edb9b4e5628744aaf9",
            "029f1bbfb9f642c180720568dae7286e",
            "30e283318ae348a9abd3762a809a581d",
            "d346cd777b604a37af568c78c5e68330",
            "3815f3c6a4dc4124837c7057c1aff7ac",
            "70dd9ef8366e4931ba170e0c4196d6f5",
            "be1e49733ac14383b31ecd7c45b84f9f",
            "1a1ea9e6701747e4bdc504345f931f3c",
            "35f2f7a163164601b63c8e25a007d22c",
            "815bc32e02394241bc1f3b40cf7d54c5",
            "c1265d739662459b8a6b246ea352b017",
            "a487ce2585dc4adaba37234970ad7761",
            "44e51efe099e4509b61687f89d701fec",
            "3f3b0604179049daa846b9a397365324",
            "88ddd1aa0b644c259a023314aaddb19a",
            "dcf30eca7a0a4674bd03922b233f01e1",
            "b5bb1941a32d46b2bb3cff74d7f8ac3b",
            "9f55d518ff1d43bcaae19b24f5c2ecb4",
            "7a6945a10b884e79b7a1032844a3d4f6",
            "0edd15c8606244099dbf07f8c9f43f08",
            "761b7644356244eca1776b9fa1970aab",
            "2afc250cb3a249f280c05ce12ccd3e88",
            "33e8c38baea247d7b738b46131796a87",
            "05c5d16c76f347168b1c7b3b9d969c38",
            "ba73fbacde66449585f6f84ad5026f3e",
            "172954103f02472faeb7a32d72208b2a",
            "f6a5c5290f53482c9d28d4a419bb3bf1",
            "ffbe05d09fc94a67ab45fd519748636f",
            "2686b3fe27524d36aabab20b9107a1ca",
            "47da660152e844ce977a4a5c4baeb249",
            "3483910d7b6144758da0e630c614ed7b",
            "c535144538c94a7c84f1817009e8ff8f",
            "5b554b605f8342358ff9618eabaafc4c",
            "36b0b38dc89f46fa9b84e68bbcd12319",
            "4766a82f34014ee3a950f65685108769",
            "18a6ff2e4bad4dbd8c0495f598906b50",
            "2a63d9e334244f6e9ec0c04d88992c2a",
            "70eb90e9a75c46ed967b64790e9232f5",
            "16c3272269704803a15c82e495164831",
            "09dff1dc49c648f69c2b0b607f08ba66",
            "7ded56a1fefa4e99b79e250c7b0e9a7c",
            "3d2740d029154eeb8a7272c3daf8eebf",
            "551bb9a913df47b5a48b2af8b6868785",
            "3ebc7f26019045258d1fd4cf0acf042e",
            "912ec256f29f4c94a82378a116833f24",
            "07d041adbcb741e98561ce79e3d53b27",
            "9f698e4c09a042a79536dd075af083bb",
            "5c7b1b3a61a148c19c02c09171136f95",
            "4f39602a5b7d4d27b06aaa29969f7d11",
            "e5736b69eace47d58eee1c64385bcf67",
            "fde97452366145dfb5b6b5e4363b027e",
            "3deda61104414d7991e803059cf2f96b",
            "b7c8103093104df9a7ad52b3589c8f2e",
            "317fc847893b46b9bb8e8dcbf8b89cf6",
            "11d79edad13342e082d4e2174693f3cd",
            "34dc033dffd2416c880250010bc85e5e",
            "56e08de25b974572ac852397707438e0",
            "1258276b669d4d8cbd4ee217e80f5e50",
            "b44a151e06604928b3089091d3ec9b80",
            "ff14303a34f642f887787f6b8bcb9547",
            "09a1e32b60c743919d8dee120fc20b76",
            "8f4195a4981442ceb5154a675c994888",
            "17fbb5c68ba34276a9be1d0630f3ff60",
            "2e60d0d6f80144049d48d3665d29b4f6",
            "2738b3ac151f49609b0dbeff04ed433e",
            "8054979056b944aabf72554bf5cf6972",
            "a857977971234d56ab7940325604f9e0",
            "dc0682ddbe474536b6190a2fc53e4ad4",
            "9d0eebe9eee340c7841daf731ca4ff20",
            "4777450b560a4383b70c0f08563e9afa",
            "b48850dcaad94320a1e7a72a5785ca74",
            "1e624bfc57e8413fbb272a22c56526cb",
            "1737025ea3a8427c9a696444f2414b5e",
            "4613657f2807415d8e8b1cda2905b6bb",
            "941a4f36cefe48fc87a5b1dc85d5ff8e",
            "5449ffb2cb7d45e089baf4c9de0ad880"
          ]
        }
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "=======================================================\n",
            "AGENTE 3 — Comunicador RAG\n",
            "=======================================================\n",
            "  [RAG] Cargando embedder...\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "cf054edc28934f45af3f634c5f2e5a86"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "  [RAG] Índice FAISS: 12 docs, dim=384\n",
            "  [GEN] Cargando generador de texto...\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "0972c7bce4d24ab7a69f209952eb4eb0"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "pytorch_model.bin:   0%|          | 0.00/2.51M [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "bf67bf2af47541a8ac25e32c6321b0b7"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Loading weights:   0%|          | 0/29 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "c1265d739662459b8a6b246ea352b017"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "[transformers] \u001b[1mGPT2LMHeadModel LOAD REPORT\u001b[0m from: sshleifer/tiny-gpt2\n",
            "Key                                   | Status     |  | \n",
            "--------------------------------------+------------+--+-\n",
            "transformer.h.{0, 1}.attn.masked_bias | UNEXPECTED |  | \n",
            "\n",
            "Notes:\n",
            "- UNEXPECTED:\tcan be ignored when loading from different task/architecture; not ok if you expect identical arch.\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "2afc250cb3a249f280c05ce12ccd3e88"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "model.safetensors:   0%|          | 0.00/2.51M [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "5b554b605f8342358ff9618eabaafc4c"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "3ebc7f26019045258d1fd4cf0acf042e"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "11d79edad13342e082d4e2174693f3cd"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "special_tokens_map.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "8054979056b944aabf72554bf5cf6972"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "  Agente 3 RAG listo\n",
            "\n",
            "[RAG] Documentos recuperados para el reporte:\n",
            "  1. Un modelo con accuracy superior al 85% es confiable para predecir rendimien...\n",
            "  2. La validación cruzada con 5 folds es el estándar para datasets medianos de ...\n",
            "  3. Los estudiantes con bajo rendimiento generalmente presentan asistencia meno...\n",
            "\n",
            "=======================================================\n",
            "REPORTE FINAL — Agente 3 RAG\n",
            "=======================================================\n",
            "Dataset: 600 estudiantes, 8 variables\n",
            "Nulos imputados: 78\n",
            "Distribución: alto=223, medio=213, bajo=164\n",
            "\n",
            "Modelos (CV 5-fold + embeddings):\n",
            "  Random Forest: 0.9833 +/- 0.0091\n",
            "  Gradient Boosting: 0.9883 +/- 0.0113\n",
            "  Logistic Regression: 0.9917 +/- 0.0075\n",
            "\n",
            "Modelo seleccionado: Logistic Regression | Accuracy: 0.9917 (99.2%)\n",
            "\n",
            "Contexto pedagógico recuperado por RAG:\n",
            "  1. Un modelo con accuracy superior al 85% es confiable para predecir rendimiento académico.\n",
            "  2. La validación cruzada con 5 folds es el estándar para datasets medianos de entre 100 y 1000 registros.\n",
            "  3. Los estudiantes con bajo rendimiento generalmente presentan asistencia menor al 65% y promedios inferiores a 5.0.\n",
            "=======================================================\n"
          ]
        }
      ],
      "source": [
        "KNOWLEDGE_BASE = [\n",
        "    \"Un rendimiento académico alto se asocia con asistencia superior al 85% y notas promedio mayores a 7.5.\",\n",
        "    \"Los estudiantes con bajo rendimiento generalmente presentan asistencia menor al 65% y promedios inferiores a 5.0.\",\n",
        "    \"La nota de matemática tiene alta correlación con el rendimiento general en ciencias exactas.\",\n",
        "    \"El turno mañana suele presentar mejores índices de rendimiento por factores de concentración y descanso.\",\n",
        "    \"La intervención temprana en estudiantes con bajo rendimiento puede revertir la situación en un cuatrimestre.\",\n",
        "    \"Un modelo con accuracy superior al 85% es confiable para predecir rendimiento académico.\",\n",
        "    \"Los embeddings semánticos capturan relaciones complejas entre variables académicas que los métodos clásicos no detectan.\",\n",
        "    \"La validación cruzada con 5 folds es el estándar para datasets medianos de entre 100 y 1000 registros.\",\n",
        "    \"El Gradient Boosting suele superar a Random Forest en datasets con variables mixtas y distribuciones sesgadas.\",\n",
        "    \"La imputación por mediana es más robusta que la media ante valores extremos en notas académicas.\",\n",
        "    \"Datasets de 600 registros permiten una validación cruzada más estable que los de 100 registros.\",\n",
        "    \"Con mayor volumen de datos, Random Forest puede igualar o superar a Gradient Boosting gracias al bagging.\",\n",
        "]\n",
        "\n",
        "\n",
        "class AgenteComunicadorRAG:\n",
        "    def __init__(self, knowledge_base):\n",
        "        print(\"=\" * 55)\n",
        "        print(\"AGENTE 3 — Comunicador RAG\")\n",
        "        print(\"=\" * 55)\n",
        "        print(\"  [RAG] Cargando embedder...\")\n",
        "        self.embedder       = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
        "        self.knowledge_base = knowledge_base\n",
        "        self._construir_indice(knowledge_base)\n",
        "        print(\"  [GEN] Cargando generador de texto...\")\n",
        "        self.generador = pipeline(\"text-generation\", model=\"sshleifer/tiny-gpt2\", max_new_tokens=60)\n",
        "        print(\"  Agente 3 RAG listo\")\n",
        "\n",
        "    def _construir_indice(self, docs):\n",
        "        embeddings  = self.embedder.encode(docs, show_progress_bar=False)\n",
        "        dim         = embeddings.shape[1]\n",
        "        self.indice = faiss.IndexFlatL2(dim)\n",
        "        self.indice.add(embeddings.astype(\"float32\"))\n",
        "        print(f\"  [RAG] Índice FAISS: {len(docs)} docs, dim={dim}\")\n",
        "\n",
        "    def recuperar(self, query, top_k=3):\n",
        "        q_emb = self.embedder.encode([query], show_progress_bar=False).astype(\"float32\")\n",
        "        _, indices = self.indice.search(q_emb, top_k)\n",
        "        return [self.knowledge_base[i] for i in indices[0]]\n",
        "\n",
        "    def responder_pregunta(self, pregunta, df_original):\n",
        "        print(f\"\\nPregunta: {pregunta}\")\n",
        "        print(\"-\" * 50)\n",
        "        docs = self.recuperar(pregunta, top_k=2)\n",
        "        dist = df_original[\"rendimiento\"].value_counts().to_dict()\n",
        "        stats = (\n",
        "            f\"Total estudiantes: {len(df_original)}. \"\n",
        "            f\"Alto: {dist.get('alto', 0)}, Medio: {dist.get('medio', 0)}, Bajo: {dist.get('bajo', 0)}. \"\n",
        "            f\"Prom. matemática: {df_original['nota_matematica'].mean():.1f}. \"\n",
        "            f\"Prom. asistencia: {df_original['asistencia_pct'].mean():.1f}%.\"\n",
        "        )\n",
        "        print(f\"Datos: {stats}\")\n",
        "        print(\"Contexto RAG recuperado:\")\n",
        "        for i, doc in enumerate(docs, 1):\n",
        "            print(f\"  {i}. {doc}\")\n",
        "\n",
        "    def generar_reporte(self, resultado, df_original):\n",
        "        mejor    = resultado[\"nombre_modelo\"]\n",
        "        acc      = resultado[\"mejor_accuracy\"]\n",
        "        metricas = resultado[\"metricas\"]\n",
        "        query    = f\"modelo {mejor} accuracy {acc:.2f} clasificacion rendimiento estudiantes\"\n",
        "        docs_ctx = self.recuperar(query, top_k=3)\n",
        "        print(\"\\n[RAG] Documentos recuperados para el reporte:\")\n",
        "        for i, doc in enumerate(docs_ctx, 1):\n",
        "            print(f\"  {i}. {doc[:75]}...\")\n",
        "        dist = df_original[\"rendimiento\"].value_counts().to_dict()\n",
        "        print(\"\\n\" + \"=\" * 55)\n",
        "        print(\"REPORTE FINAL — Agente 3 RAG\")\n",
        "        print(\"=\" * 55)\n",
        "        print(f\"Dataset: {len(df_original)} estudiantes, {df_original.shape[1]} variables\")\n",
        "        print(f\"Nulos imputados: {df_original.isnull().sum().sum()}\")\n",
        "        print(f\"Distribución: alto={dist.get('alto',0)}, medio={dist.get('medio',0)}, bajo={dist.get('bajo',0)}\")\n",
        "        print()\n",
        "        print(\"Modelos (CV 5-fold + embeddings):\")\n",
        "        for nombre, m in metricas.items():\n",
        "            print(f\"  {nombre}: {m['accuracy_media']} +/- {m['std']}\")\n",
        "        print(f\"\\nModelo seleccionado: {mejor} | Accuracy: {acc:.4f} ({acc*100:.1f}%)\")\n",
        "        print()\n",
        "        print(\"Contexto pedagógico recuperado por RAG:\")\n",
        "        for i, doc in enumerate(docs_ctx, 1):\n",
        "            print(f\"  {i}. {doc}\")\n",
        "        print(\"=\" * 55)\n",
        "\n",
        "\n",
        "agente3 = AgenteComunicadorRAG(KNOWLEDGE_BASE)\n",
        "agente3.generar_reporte(resultado, df_raw)"
      ]
    }
  ]
}