{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO8FQ6lZfSSwJIAhR+u9mmR",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Giovasosa/Tarea-IA/blob/main/multiagentes.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "nK_PpygreDA2"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "f1402e84"
      },
      "outputs": [],
      "source": [
        "!pip install -q transformers sentence-transformers scikit-learn pandas numpy torch faiss-cpu"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "bdac46d0"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import io\n",
        "import faiss\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
        "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.model_selection import cross_val_score\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from transformers import pipeline"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 404
        },
        "id": "1e563d79",
        "outputId": "4d95d970-cd02-4d1b-bef2-ea630438451f"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dataset: 600 filas x 8 columnas (4800 celdas)\n",
            "Valores nulos: 78\n",
            "rendimiento\n",
            "alto     223\n",
            "medio    213\n",
            "bajo     164\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "     nombre  edad  nota_matematica  nota_lengua  nota_ciencias  \\\n",
              "0     Ana_1    17              7.9          6.0            7.5   \n",
              "1   Bruno_2    18              6.0          3.6            5.2   \n",
              "2   Carla_3    16              5.9          6.4            5.9   \n",
              "3   Diego_4    18              3.5          4.0            3.5   \n",
              "4   Elena_5    18              NaN          4.6            3.3   \n",
              "5  Franco_6    15             10.0          9.2            7.5   \n",
              "6  Gisela_7    16              3.4          3.9            4.2   \n",
              "7  Hernan_8    16              5.7          6.9            5.0   \n",
              "\n",
              "   asistencia_pct   turno rendimiento  \n",
              "0            76.5   tarde       medio  \n",
              "1            71.0  manana        bajo  \n",
              "2            74.1   tarde       medio  \n",
              "3            48.6   tarde        bajo  \n",
              "4            63.1  manana        bajo  \n",
              "5            92.8   tarde        alto  \n",
              "6            60.7   tarde        bajo  \n",
              "7            69.2  manana       medio  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-df7121ff-0600-4520-bd8c-149c976587e9\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>nombre</th>\n",
              "      <th>edad</th>\n",
              "      <th>nota_matematica</th>\n",
              "      <th>nota_lengua</th>\n",
              "      <th>nota_ciencias</th>\n",
              "      <th>asistencia_pct</th>\n",
              "      <th>turno</th>\n",
              "      <th>rendimiento</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Ana_1</td>\n",
              "      <td>17</td>\n",
              "      <td>7.9</td>\n",
              "      <td>6.0</td>\n",
              "      <td>7.5</td>\n",
              "      <td>76.5</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Bruno_2</td>\n",
              "      <td>18</td>\n",
              "      <td>6.0</td>\n",
              "      <td>3.6</td>\n",
              "      <td>5.2</td>\n",
              "      <td>71.0</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Carla_3</td>\n",
              "      <td>16</td>\n",
              "      <td>5.9</td>\n",
              "      <td>6.4</td>\n",
              "      <td>5.9</td>\n",
              "      <td>74.1</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Diego_4</td>\n",
              "      <td>18</td>\n",
              "      <td>3.5</td>\n",
              "      <td>4.0</td>\n",
              "      <td>3.5</td>\n",
              "      <td>48.6</td>\n",
              "      <td>tarde</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Elena_5</td>\n",
              "      <td>18</td>\n",
              "      <td>NaN</td>\n",
              "      <td>4.6</td>\n",
              "      <td>3.3</td>\n",
              "      <td>63.1</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>Franco_6</td>\n",
              "      <td>15</td>\n",
              "      <td>10.0</td>\n",
              "      <td>9.2</td>\n",
              "      <td>7.5</td>\n",
              "      <td>92.8</td>\n",
              "      <td>tarde</td>\n",
              "      <td>alto</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>Gisela_7</td>\n",
              "      <td>16</td>\n",
              "      <td>3.4</td>\n",
              "      <td>3.9</td>\n",
              "      <td>4.2</td>\n",
              "      <td>60.7</td>\n",
              "      <td>tarde</td>\n",
              "      <td>bajo</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>Hernan_8</td>\n",
              "      <td>16</td>\n",
              "      <td>5.7</td>\n",
              "      <td>6.9</td>\n",
              "      <td>5.0</td>\n",
              "      <td>69.2</td>\n",
              "      <td>manana</td>\n",
              "      <td>medio</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-df7121ff-0600-4520-bd8c-149c976587e9')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-df7121ff-0600-4520-bd8c-149c976587e9 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-df7121ff-0600-4520-bd8c-149c976587e9');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_raw",
              "summary": "{\n  \"name\": \"df_raw\",\n  \"rows\": 600,\n  \"fields\": [\n    {\n      \"column\": \"nombre\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 600,\n        \"samples\": [\n          \"Karen_111\",\n          \"Tomas_420\",\n          \"Pablo_566\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"edad\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 14,\n        \"max\": 18,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          18,\n          14,\n          16\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_matematica\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2.1107708594993513,\n        \"min\": 1.0,\n        \"max\": 10.0,\n        \"num_unique_values\": 83,\n        \"samples\": [\n          2.4,\n          7.9,\n          4.3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_lengua\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.9252192845175486,\n        \"min\": 1.5,\n        \"max\": 10.0,\n        \"num_unique_values\": 79,\n        \"samples\": [\n          5.0,\n          6.0,\n          7.2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_ciencias\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2.0160845668464216,\n        \"min\": 1.0,\n        \"max\": 10.0,\n        \"num_unique_values\": 84,\n        \"samples\": [\n          1.0,\n          7.5,\n          7.4\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"asistencia_pct\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 15.111630872220658,\n        \"min\": 40.0,\n        \"max\": 100.0,\n        \"num_unique_values\": 340,\n        \"samples\": [\n          60.4,\n          48.2,\n          62.6\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"turno\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"manana\",\n          \"tarde\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"rendimiento\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"medio\",\n          \"bajo\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 3
        }
      ],
      "source": [
        "def generar_dataset(n: int = 600, seed: int = 42) -> pd.DataFrame:\n",
        "    \"\"\"Genera un dataset sintético de estudiantes con ~5 % de nulos.\"\"\"\n",
        "    np.random.seed(seed)\n",
        "\n",
        "    nombres_base = [\n",
        "        \"Ana\", \"Bruno\", \"Carla\", \"Diego\", \"Elena\", \"Franco\", \"Gisela\",\n",
        "        \"Hernan\", \"Ivana\", \"Juan\", \"Karen\", \"Lucas\", \"Maria\", \"Nicolas\",\n",
        "        \"Olivia\", \"Pablo\", \"Quimey\", \"Rodrigo\", \"Sofia\", \"Tomas\",\n",
        "        \"Valentina\", \"Walter\", \"Ximena\", \"Yamila\", \"Zaira\", \"Agustin\",\n",
        "        \"Belen\", \"Cesar\", \"Daniela\", \"Emilio\", \"Florencia\", \"Gaston\",\n",
        "        \"Hilda\", \"Ignacio\", \"Julia\", \"Kevin\", \"Lorena\", \"Marcos\",\n",
        "        \"Noelia\", \"Omar\", \"Patricia\", \"Quintin\", \"Raquel\", \"Santiago\",\n",
        "        \"Teresa\", \"Uriel\", \"Veronica\", \"William\", \"Ximena\", \"Yolanda\",\n",
        "    ]\n",
        "\n",
        "    nombres   = [f\"{nombres_base[i % len(nombres_base)]}_{i + 1}\" for i in range(n)]\n",
        "    edades    = np.random.randint(14, 19, size=n)\n",
        "    turnos    = np.random.choice([\"manana\", \"tarde\"], size=n, p=[0.55, 0.45])\n",
        "\n",
        "    rendimiento_list, nota_mat, nota_len, nota_cie, asistencia = [], [], [], [], []\n",
        "\n",
        "    for i in range(n):\n",
        "        bonus = 0.3 if turnos[i] == \"manana\" else 0.0\n",
        "        r = np.random.choice([\"alto\", \"medio\", \"bajo\"], p=[0.35, 0.35, 0.30])\n",
        "        rendimiento_list.append(r)\n",
        "\n",
        "        if r == \"alto\":\n",
        "            nota_mat.append(round(np.clip(np.random.normal(8.5 + bonus, 0.8), 7.0, 10.0), 1))\n",
        "            nota_len.append(round(np.clip(np.random.normal(8.5 + bonus, 0.7), 7.0, 10.0), 1))\n",
        "            nota_cie.append(round(np.clip(np.random.normal(8.3 + bonus, 0.9), 7.0, 10.0), 1))\n",
        "            asistencia.append(round(np.clip(np.random.normal(92, 5), 80, 100), 1))\n",
        "        elif r == \"medio\":\n",
        "            nota_mat.append(round(np.clip(np.random.normal(6.5, 0.9), 5.0, 8.5), 1))\n",
        "            nota_len.append(round(np.clip(np.random.normal(6.8, 0.8), 5.0, 8.5), 1))\n",
        "            nota_cie.append(round(np.clip(np.random.normal(6.5, 1.0), 5.0, 8.5), 1))\n",
        "            asistencia.append(round(np.clip(np.random.normal(78, 7), 65, 90), 1))\n",
        "        else:\n",
        "            nota_mat.append(round(np.clip(np.random.normal(4.0, 1.0), 1.0, 6.0), 1))\n",
        "            nota_len.append(round(np.clip(np.random.normal(4.2, 0.9), 1.0, 6.0), 1))\n",
        "            nota_cie.append(round(np.clip(np.random.normal(3.9, 1.1), 1.0, 6.0), 1))\n",
        "            asistencia.append(round(np.clip(np.random.normal(58, 8), 40, 72), 1))\n",
        "\n",
        "    nota_mat_arr = np.array(nota_mat, dtype=float)\n",
        "    nota_len_arr = np.array(nota_len, dtype=float)\n",
        "    nota_cie_arr = np.array(nota_cie, dtype=float)\n",
        "\n",
        "    nota_mat_arr[np.random.choice(n, size=int(n * 0.05), replace=False)] = np.nan\n",
        "    nota_len_arr[np.random.choice(n, size=int(n * 0.04), replace=False)] = np.nan\n",
        "    nota_cie_arr[np.random.choice(n, size=int(n * 0.04), replace=False)] = np.nan\n",
        "\n",
        "    df = pd.DataFrame({\n",
        "        \"nombre\":          nombres,\n",
        "        \"edad\":            edades,\n",
        "        \"nota_matematica\": nota_mat_arr,\n",
        "        \"nota_lengua\":     nota_len_arr,\n",
        "        \"nota_ciencias\":   nota_cie_arr,\n",
        "        \"asistencia_pct\":  asistencia,\n",
        "        \"turno\":           turnos,\n",
        "        \"rendimiento\":     rendimiento_list,\n",
        "    })\n",
        "\n",
        "    print(f\"Dataset: {df.shape[0]} filas x {df.shape[1]} columnas ({df.size} celdas)\")\n",
        "    print(f\"Valores nulos: {df.isnull().sum().sum()}\")\n",
        "    print(df['rendimiento'].value_counts().to_string())\n",
        "    return df\n",
        "\n",
        "df_raw = generar_dataset(n=600, seed=42)\n",
        "df_raw.head(8)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 414
        },
        "id": "58326945",
        "outputId": "beaa1223-8fb3-4ae1-e6bf-f53a70caf2a6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "=======================================================\n",
            "AGENTE 1 — Normalizador\n",
            "=======================================================\n",
            "  [Limpieza] Nulos encontrados: 78\n",
            "  [Imputación] 'nota_matematica' -> mediana (6.80)\n",
            "  [Imputación] 'nota_lengua' -> mediana (7.10)\n",
            "  [Imputación] 'nota_ciencias' -> mediana (6.70)\n",
            "  [Codificación] 'turno' -> ['manana', 'tarde']\n",
            "  [Codificación] 'rendimiento' -> [np.str_('alto'), np.str_('bajo'), np.str_('medio')]\n",
            "  [Escalado] StandardScaler en: ['edad', 'nota_matematica', 'nota_lengua', 'nota_ciencias', 'asistencia_pct']\n",
            "\n",
            "Dataset limpio: (600, 10)\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "    nombre      edad  nota_matematica  nota_lengua  nota_ciencias  \\\n",
              "0    Ana_1  0.683739         0.634225    -0.456422       0.482130   \n",
              "1  Bruno_2  1.380247        -0.289876    -1.729417      -0.683088   \n",
              "2  Carla_3 -0.012769        -0.338513    -0.244256      -0.328457   \n",
              "3  Diego_4  1.380247        -1.505798    -1.517251      -1.544337   \n",
              "4  Elena_5  1.380247         0.099219    -1.199002      -1.645660   \n",
              "\n",
              "   asistencia_pct   turno rendimiento  turno_enc  rendimiento_enc  \n",
              "0       -0.086948   tarde       medio          1                2  \n",
              "1       -0.451210  manana        bajo          0                1  \n",
              "2       -0.245899   tarde       medio          1                2  \n",
              "3       -1.934749   tarde        bajo          1                1  \n",
              "4       -0.974422  manana        bajo          0                1  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>nombre</th>\n",
              "      <th>edad</th>\n",
              "      <th>nota_matematica</th>\n",
              "      <th>nota_lengua</th>\n",
              "      <th>nota_ciencias</th>\n",
              "      <th>asistencia_pct</th>\n",
              "      <th>turno</th>\n",
              "      <th>rendimiento</th>\n",
              "      <th>turno_enc</th>\n",
              "      <th>rendimiento_enc</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Ana_1</td>\n",
              "      <td>0.683739</td>\n",
              "      <td>0.634225</td>\n",
              "      <td>-0.456422</td>\n",
              "      <td>0.482130</td>\n",
              "      <td>-0.086948</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "      <td>1</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Bruno_2</td>\n",
              "      <td>1.380247</td>\n",
              "      <td>-0.289876</td>\n",
              "      <td>-1.729417</td>\n",
              "      <td>-0.683088</td>\n",
              "      <td>-0.451210</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Carla_3</td>\n",
              "      <td>-0.012769</td>\n",
              "      <td>-0.338513</td>\n",
              "      <td>-0.244256</td>\n",
              "      <td>-0.328457</td>\n",
              "      <td>-0.245899</td>\n",
              "      <td>tarde</td>\n",
              "      <td>medio</td>\n",
              "      <td>1</td>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Diego_4</td>\n",
              "      <td>1.380247</td>\n",
              "      <td>-1.505798</td>\n",
              "      <td>-1.517251</td>\n",
              "      <td>-1.544337</td>\n",
              "      <td>-1.934749</td>\n",
              "      <td>tarde</td>\n",
              "      <td>bajo</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Elena_5</td>\n",
              "      <td>1.380247</td>\n",
              "      <td>0.099219</td>\n",
              "      <td>-1.199002</td>\n",
              "      <td>-1.645660</td>\n",
              "      <td>-0.974422</td>\n",
              "      <td>manana</td>\n",
              "      <td>bajo</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-7fbdf57a-da99-49f9-a156-f7bc1f3a129a');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_limpio",
              "summary": "{\n  \"name\": \"df_limpio\",\n  \"rows\": 600,\n  \"fields\": [\n    {\n      \"column\": \"nombre\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 600,\n        \"samples\": [\n          \"Karen_111\",\n          \"Tomas_420\",\n          \"Pablo_566\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"edad\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488732,\n        \"min\": -1.4057855414930898,\n        \"max\": 1.380246910681488,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          1.380246910681488,\n          -1.4057855414930898,\n          -0.012769315405800908\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_matematica\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488719,\n        \"min\": -2.7217207755665975,\n        \"max\": 1.6555999857092034,\n        \"num_unique_values\": 83,\n        \"samples\": [\n          -2.0408042127014734,\n          0.6342251414115166,\n          0.43967755202148084\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_lengua\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488723,\n        \"min\": -2.8432872660777737,\n        \"max\": 1.665236521192272,\n        \"num_unique_values\": 79,\n        \"samples\": [\n          -0.9868362948489313,\n          -0.4564217316406906,\n          0.18007574420919825\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"nota_ciencias\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488725,\n        \"min\": -2.8108785317945593,\n        \"max\": 1.7486721055411636,\n        \"num_unique_values\": 84,\n        \"samples\": [\n          -1.7469833830828907,\n          0.48213026183679614,\n          -0.7337499081193969\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"asistencia_pct\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0008343764488714,\n        \"min\": -2.5043215911593095,\n        \"max\": 1.4694429280178285,\n        \"num_unique_values\": 340,\n        \"samples\": [\n          -1.153241654639083,\n          -1.9612404402051007,\n          -1.0075369556025875\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"turno\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"manana\",\n          \"tarde\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"rendimiento\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"medio\",\n          \"bajo\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"turno_enc\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"rendimiento_enc\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 2,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          2,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 4
        }
      ],
      "source": [
        "class AgenteNormalizador:\n",
        "    def __init__(self):\n",
        "        self.scaler         = StandardScaler()\n",
        "        self.label_encoders = {}\n",
        "        self.log            = []\n",
        "\n",
        "    def limpiar(self, df):\n",
        "        nulos = df.isnull().sum().sum()\n",
        "        df    = df.drop_duplicates()\n",
        "        self.log.append(f\"[Limpieza] Nulos encontrados: {nulos}\")\n",
        "        return df\n",
        "\n",
        "    def imputar(self, df):\n",
        "        for col in df.columns:\n",
        "            if df[col].isnull().any():\n",
        "                if df[col].dtype in [\"float64\", \"int64\"]:\n",
        "                    val = df[col].median()\n",
        "                    df[col] = df[col].fillna(val)\n",
        "                    self.log.append(f\"[Imputación] '{col}' -> mediana ({val:.2f})\")\n",
        "                else:\n",
        "                    val = df[col].mode()[0]\n",
        "                    df[col] = df[col].fillna(val)\n",
        "                    self.log.append(f\"[Imputación] '{col}' -> moda ('{val}')\")\n",
        "        return df\n",
        "\n",
        "    def codificar(self, df, cols):\n",
        "        for col in cols:\n",
        "            le = LabelEncoder()\n",
        "            df[col + \"_enc\"] = le.fit_transform(df[col].astype(str))\n",
        "            self.label_encoders[col] = le\n",
        "            self.log.append(f\"[Codificación] '{col}' -> {list(le.classes_)}\")\n",
        "        return df\n",
        "\n",
        "    def escalar(self, df, cols):\n",
        "        df[cols] = self.scaler.fit_transform(df[cols])\n",
        "        self.log.append(f\"[Escalado] StandardScaler en: {cols}\")\n",
        "        return df\n",
        "\n",
        "    def procesar(self, df):\n",
        "        print(\"=\" * 55)\n",
        "        print(\"AGENTE 1 — Normalizador\")\n",
        "        print(\"=\" * 55)\n",
        "        df = self.limpiar(df.copy())\n",
        "        df = self.imputar(df)\n",
        "        df = self.codificar(df, [\"turno\", \"rendimiento\"])\n",
        "        df = self.escalar(df, [\"edad\", \"nota_matematica\", \"nota_lengua\", \"nota_ciencias\", \"asistencia_pct\"])\n",
        "        for e in self.log:\n",
        "            print(\" \", e)\n",
        "        print(f\"\\nDataset limpio: {df.shape}\")\n",
        "        return df\n",
        "\n",
        "agente1   = AgenteNormalizador()\n",
        "df_limpio = agente1.procesar(df_raw)\n",
        "df_limpio.head()"
      ]
    }
  ]
}