# -*- coding: utf-8 -*-
"""multiagente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5XSlpoh-EJ3PpEwazBM3NvsEvMIZEXf
"""



!pip install -q transformers sentence-transformers scikit-learn pandas numpy torch faiss-cpu

import pandas as pd
import numpy as np
import io
import faiss
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sentence_transformers import SentenceTransformer
from transformers import pipeline

def generar_dataset(n: int = 600, seed: int = 42) -> pd.DataFrame:
    """Genera un dataset sintético de estudiantes con ~5 % de nulos."""
    np.random.seed(seed)

    nombres_base = [
        "Ana", "Bruno", "Carla", "Diego", "Elena", "Franco", "Gisela",
        "Hernan", "Ivana", "Juan", "Karen", "Lucas", "Maria", "Nicolas",
        "Olivia", "Pablo", "Quimey", "Rodrigo", "Sofia", "Tomas",
        "Valentina", "Walter", "Ximena", "Yamila", "Zaira", "Agustin",
        "Belen", "Cesar", "Daniela", "Emilio", "Florencia", "Gaston",
        "Hilda", "Ignacio", "Julia", "Kevin", "Lorena", "Marcos",
        "Noelia", "Omar", "Patricia", "Quintin", "Raquel", "Santiago",
        "Teresa", "Uriel", "Veronica", "William", "Ximena", "Yolanda",
    ]

    nombres   = [f"{nombres_base[i % len(nombres_base)]}_{i + 1}" for i in range(n)]
    edades    = np.random.randint(14, 19, size=n)
    turnos    = np.random.choice(["manana", "tarde"], size=n, p=[0.55, 0.45])

    rendimiento_list, nota_mat, nota_len, nota_cie, asistencia = [], [], [], [], []

    for i in range(n):
        bonus = 0.3 if turnos[i] == "manana" else 0.0
        r = np.random.choice(["alto", "medio", "bajo"], p=[0.35, 0.35, 0.30])
        rendimiento_list.append(r)

        if r == "alto":
            nota_mat.append(round(np.clip(np.random.normal(8.5 + bonus, 0.8), 7.0, 10.0), 1))
            nota_len.append(round(np.clip(np.random.normal(8.5 + bonus, 0.7), 7.0, 10.0), 1))
            nota_cie.append(round(np.clip(np.random.normal(8.3 + bonus, 0.9), 7.0, 10.0), 1))
            asistencia.append(round(np.clip(np.random.normal(92, 5), 80, 100), 1))
        elif r == "medio":
            nota_mat.append(round(np.clip(np.random.normal(6.5, 0.9), 5.0, 8.5), 1))
            nota_len.append(round(np.clip(np.random.normal(6.8, 0.8), 5.0, 8.5), 1))
            nota_cie.append(round(np.clip(np.random.normal(6.5, 1.0), 5.0, 8.5), 1))
            asistencia.append(round(np.clip(np.random.normal(78, 7), 65, 90), 1))
        else:
            nota_mat.append(round(np.clip(np.random.normal(4.0, 1.0), 1.0, 6.0), 1))
            nota_len.append(round(np.clip(np.random.normal(4.2, 0.9), 1.0, 6.0), 1))
            nota_cie.append(round(np.clip(np.random.normal(3.9, 1.1), 1.0, 6.0), 1))
            asistencia.append(round(np.clip(np.random.normal(58, 8), 40, 72), 1))

    nota_mat_arr = np.array(nota_mat, dtype=float)
    nota_len_arr = np.array(nota_len, dtype=float)
    nota_cie_arr = np.array(nota_cie, dtype=float)

    nota_mat_arr[np.random.choice(n, size=int(n * 0.05), replace=False)] = np.nan
    nota_len_arr[np.random.choice(n, size=int(n * 0.04), replace=False)] = np.nan
    nota_cie_arr[np.random.choice(n, size=int(n * 0.04), replace=False)] = np.nan

    df = pd.DataFrame({
        "nombre":          nombres,
        "edad":            edades,
        "nota_matematica": nota_mat_arr,
        "nota_lengua":     nota_len_arr,
        "nota_ciencias":   nota_cie_arr,
        "asistencia_pct":  asistencia,
        "turno":           turnos,
        "rendimiento":     rendimiento_list,
    })

    print(f"Dataset: {df.shape[0]} filas x {df.shape[1]} columnas ({df.size} celdas)")
    print(f"Valores nulos: {df.isnull().sum().sum()}")
    print(df['rendimiento'].value_counts().to_string())
    return df

df_raw = generar_dataset(n=600, seed=42)
df_raw.head(8)

class AgenteNormalizador:
    def __init__(self):
        self.scaler         = StandardScaler()
        self.label_encoders = {}
        self.log            = []

    def limpiar(self, df):
        nulos = df.isnull().sum().sum()
        df    = df.drop_duplicates()
        self.log.append(f"[Limpieza] Nulos encontrados: {nulos}")
        return df

    def imputar(self, df):
        for col in df.columns:
            if df[col].isnull().any():
                if df[col].dtype in ["float64", "int64"]:
                    val = df[col].median()
                    df[col] = df[col].fillna(val)
                    self.log.append(f"[Imputación] '{col}' -> mediana ({val:.2f})")
                else:
                    val = df[col].mode()[0]
                    df[col] = df[col].fillna(val)
                    self.log.append(f"[Imputación] '{col}' -> moda ('{val}')")
        return df

    def codificar(self, df, cols):
        for col in cols:
            le = LabelEncoder()
            df[col + "_enc"] = le.fit_transform(df[col].astype(str))
            self.label_encoders[col] = le
            self.log.append(f"[Codificación] '{col}' -> {list(le.classes_)}")
        return df

    def escalar(self, df, cols):
        df[cols] = self.scaler.fit_transform(df[cols])
        self.log.append(f"[Escalado] StandardScaler en: {cols}")
        return df

    def procesar(self, df):
        print("=" * 55)
        print("AGENTE 1 — Normalizador")
        print("=" * 55)
        df = self.limpiar(df.copy())
        df = self.imputar(df)
        df = self.codificar(df, ["turno", "rendimiento"])
        df = self.escalar(df, ["edad", "nota_matematica", "nota_lengua", "nota_ciencias", "asistencia_pct"])
        for e in self.log:
            print(" ", e)
        print(f"\nDataset limpio: {df.shape}")
        return df

agente1   = AgenteNormalizador()
df_limpio = agente1.procesar(df_raw)
df_limpio.head()

class AgenteEntrenador:
    def __init__(self, modelo_emb="all-MiniLM-L6-v2"):
        print("=" * 55)
        print("AGENTE 2 — Entrenador")
        print("=" * 55)
        print(f"  Cargando embedder: {modelo_emb}")
        self.embedder      = SentenceTransformer(modelo_emb)
        self.mejor_modelo  = None
        self.mejor_score   = 0
        self.mejor_nombre  = ""
        self.metricas      = {}

    def generar_embeddings(self, df_orig):
        print("\n  [Embeddings] Generando representaciones semánticas...")
        textos = df_orig.apply(
            lambda r: (
                f"estudiante de {r['edad']} anios, turno {r['turno']}, "
                f"notas: matematica {r['nota_matematica']}, "
                f"lengua {r['nota_lengua']}, ciencias {r['nota_ciencias']}, "
                f"asistencia {r['asistencia_pct']}%"
            ),
            axis=1,
        ).tolist()
        emb = self.embedder.encode(textos, show_progress_bar=False)
        print(f"  [Embeddings] Shape: {emb.shape}")
        return emb

    def construir_features(self, df, emb):
        cols = ["edad", "nota_matematica", "nota_lengua", "nota_ciencias", "asistencia_pct", "turno_enc"]
        X = np.hstack([df[cols].values, emb])
        print(f"  [Features] {len(cols)} numéricas + {emb.shape[1]} embedding = {X.shape[1]} total")
        return X

    def entrenar(self, X, y):
        print("\n  [Entrenamiento] Validación cruzada cv=5:")
        candidatos = {
            "Random Forest":       RandomForestClassifier(n_estimators=100, random_state=42),
            "Gradient Boosting":   GradientBoostingClassifier(n_estimators=100, random_state=42),
            "Logistic Regression": LogisticRegression(max_iter=500, random_state=42),
        }
        for nombre, modelo in candidatos.items():
            scores = cross_val_score(modelo, X, y, cv=5, scoring="accuracy")
            m, s   = scores.mean(), scores.std()
            self.metricas[nombre] = {"accuracy_media": round(m, 4), "std": round(s, 4)}
            print(f"    {nombre}: {m:.4f} +/- {s:.4f}")
            if m > self.mejor_score:
                self.mejor_score  = m
                self.mejor_nombre = nombre
                self.mejor_modelo = modelo
        self.mejor_modelo.fit(X, y)
        print(f"\n  Mejor modelo: {self.mejor_nombre} ({self.mejor_score:.4f})")

    def procesar(self, df, df_orig):
        emb = self.generar_embeddings(df_orig)
        X   = self.construir_features(df, emb)
        y   = df["rendimiento_enc"].values
        self.entrenar(X, y)
        return {
            "modelo":         self.mejor_modelo,
            "nombre_modelo":  self.mejor_nombre,
            "metricas":       self.metricas,
            "mejor_accuracy": self.mejor_score,
            "X": X, "y": y,
        }

agente2   = AgenteEntrenador()
resultado = agente2.procesar(df_limpio, df_raw)

KNOWLEDGE_BASE = [
    "Un rendimiento académico alto se asocia con asistencia superior al 85% y notas promedio mayores a 7.5.",
    "Los estudiantes con bajo rendimiento generalmente presentan asistencia menor al 65% y promedios inferiores a 5.0.",
    "La nota de matemática tiene alta correlación con el rendimiento general en ciencias exactas.",
    "El turno mañana suele presentar mejores índices de rendimiento por factores de concentración y descanso.",
    "La intervención temprana en estudiantes con bajo rendimiento puede revertir la situación en un cuatrimestre.",
    "Un modelo con accuracy superior al 85% es confiable para predecir rendimiento académico.",
    "Los embeddings semánticos capturan relaciones complejas entre variables académicas que los métodos clásicos no detectan.",
    "La validación cruzada con 5 folds es el estándar para datasets medianos de entre 100 y 1000 registros.",
    "El Gradient Boosting suele superar a Random Forest en datasets con variables mixtas y distribuciones sesgadas.",
    "La imputación por mediana es más robusta que la media ante valores extremos en notas académicas.",
    "Datasets de 600 registros permiten una validación cruzada más estable que los de 100 registros.",
    "Con mayor volumen de datos, Random Forest puede igualar o superar a Gradient Boosting gracias al bagging.",
]


class AgenteComunicadorRAG:
    def __init__(self, knowledge_base):
        print("=" * 55)
        print("AGENTE 3 — Comunicador RAG")
        print("=" * 55)
        print("  [RAG] Cargando embedder...")
        self.embedder       = SentenceTransformer("all-MiniLM-L6-v2")
        self.knowledge_base = knowledge_base
        self._construir_indice(knowledge_base)
        print("  [GEN] Cargando generador de texto...")
        self.generador = pipeline("text-generation", model="sshleifer/tiny-gpt2", max_new_tokens=60)
        print("  Agente 3 RAG listo")

    def _construir_indice(self, docs):
        embeddings  = self.embedder.encode(docs, show_progress_bar=False)
        dim         = embeddings.shape[1]
        self.indice = faiss.IndexFlatL2(dim)
        self.indice.add(embeddings.astype("float32"))
        print(f"  [RAG] Índice FAISS: {len(docs)} docs, dim={dim}")

    def recuperar(self, query, top_k=3):
        q_emb = self.embedder.encode([query], show_progress_bar=False).astype("float32")
        _, indices = self.indice.search(q_emb, top_k)
        return [self.knowledge_base[i] for i in indices[0]]

    def responder_pregunta(self, pregunta, df_original):
        print(f"\nPregunta: {pregunta}")
        print("-" * 50)
        docs = self.recuperar(pregunta, top_k=2)
        dist = df_original["rendimiento"].value_counts().to_dict()
        stats = (
            f"Total estudiantes: {len(df_original)}. "
            f"Alto: {dist.get('alto', 0)}, Medio: {dist.get('medio', 0)}, Bajo: {dist.get('bajo', 0)}. "
            f"Prom. matemática: {df_original['nota_matematica'].mean():.1f}. "
            f"Prom. asistencia: {df_original['asistencia_pct'].mean():.1f}%."
        )
        print(f"Datos: {stats}")
        print("Contexto RAG recuperado:")
        for i, doc in enumerate(docs, 1):
            print(f"  {i}. {doc}")

    def generar_reporte(self, resultado, df_original):
        mejor    = resultado["nombre_modelo"]
        acc      = resultado["mejor_accuracy"]
        metricas = resultado["metricas"]
        query    = f"modelo {mejor} accuracy {acc:.2f} clasificacion rendimiento estudiantes"
        docs_ctx = self.recuperar(query, top_k=3)
        print("\n[RAG] Documentos recuperados para el reporte:")
        for i, doc in enumerate(docs_ctx, 1):
            print(f"  {i}. {doc[:75]}...")
        dist = df_original["rendimiento"].value_counts().to_dict()
        print("\n" + "=" * 55)
        print("REPORTE FINAL — Agente 3 RAG")
        print("=" * 55)
        print(f"Dataset: {len(df_original)} estudiantes, {df_original.shape[1]} variables")
        print(f"Nulos imputados: {df_original.isnull().sum().sum()}")
        print(f"Distribución: alto={dist.get('alto',0)}, medio={dist.get('medio',0)}, bajo={dist.get('bajo',0)}")
        print()
        print("Modelos (CV 5-fold + embeddings):")
        for nombre, m in metricas.items():
            print(f"  {nombre}: {m['accuracy_media']} +/- {m['std']}")
        print(f"\nModelo seleccionado: {mejor} | Accuracy: {acc:.4f} ({acc*100:.1f}%)")
        print()
        print("Contexto pedagógico recuperado por RAG:")
        for i, doc in enumerate(docs_ctx, 1):
            print(f"  {i}. {doc}")
        print("=" * 55)


agente3 = AgenteComunicadorRAG(KNOWLEDGE_BASE)
agente3.generar_reporte(resultado, df_raw)

agente3.responder_pregunta(
    "Cuántos estudiantes tienen bajo rendimiento y qué se puede hacer?",
    df_raw
)

agente3.responder_pregunta(
    "Es confiable el modelo para predecir rendimiento?",
    df_raw
)

# Cambia esta pregunta por lo que quieras consultar
mi_pregunta = "Qué relación hay entre asistencia y notas de matemática?"
agente3.responder_pregunta(mi_pregunta, df_raw)